//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFProject.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEALS
    {
        public int ID_DEAL { get; set; }
        public Nullable<int> ID_REAL { get; set; }
        public Nullable<int> ID_CLIENT { get; set; }
        public Nullable<int> ID_PROPOSAL { get; set; }
        public Nullable<System.DateTime> DATA_DEALS { get; set; }
        public Nullable<decimal> COMM_REAL { get; set; }
    
        public virtual PEOPLE PEOPLE { get; set; }
        public virtual PEOPLE PEOPLE1 { get; set; }
        public virtual PROPOSALS PROPOSALS { get; set; }
    }
}
