//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFProject.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Real_Estate_AgencyEntities : DbContext
    {
        public Real_Estate_AgencyEntities()
            : base("name=Real_Estate_AgencyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AREAS> AREAS { get; set; }
        public virtual DbSet<DEALS> DEALS { get; set; }
        public virtual DbSet<PEOPLE> PEOPLE { get; set; }
        public virtual DbSet<PROPOSALS> PROPOSALS { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TYPE_OBJECTS> TYPE_OBJECTS { get; set; }
        public virtual DbSet<USERS_TABLE> USERS_TABLE { get; set; }
    }
}
